services:

  db:
    image: postgres
    container_name: dev-postgres
    env_file: .env.dev
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d  ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"

  api:
    container_name: dev-api
    restart: always
    build: . 
    env_file: .env.dev
    environment:
      - POSTGRES_HOST=db
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${CONTAINER_PORT}:3000"
