type Comment {
  id: ID!
  articleId: ID!
  authorId: ID!
  authorUsername: String!
  content: String!
  createdAt: String!
  score: Int!
  children: [Comment!]!
}

type Query {
  getComments(limit: Int): [Comment!]!
}

type Mutation {
  createComment(articleId: ID!, content: String!): Comment!
  answerComment(commentId: ID!, content: String!): Comment!
  upVoteComment(commentId: ID!): Boolean
  downVoteComment(commentId: ID!): Boolean
}
