type Comment {
  id: ID!
  articleId: ID!
  authorId: ID!
  content: String!
  createdAt: String!
  score: Int!
  children: [Comment]!
}

type Query {
  getComments(limit: Int): [Comment!]
}

type Mutation {
  createComment(articleId: String!, content: String!): Comment!
  answerComment(commentId: String!, content: String!): Comment!
  upVoteComment(commentId: Int): Boolean
  downVoteComment(commentId: Int): Boolean
}
